FROM nginx:1.15.0-alpine

#remove default config file
RUN rm /etc/nginx/conf.d/default.conf

#copy my config file to nginx
COPY nginx.conf /etc/nginx/conf.d

#to nginx work we need create one file .php 
#if not created the file will give error 404
RUN mkdir /var/www/html -p && touch /var/www/html/index.php